import 'package:eduflow_core/eduflow_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';

final facultyLeavesProvider = FutureProvider<List<Map<String, dynamic>>>((ref) async {
  final response = await ref.watch(dioClientProvider).dio.get('/faculty/me/leave-requests');
  final body = Map<String, dynamic>.from(response.data as Map);
  return (body['data'] as List? ?? const []).whereType<Map>().map((row) => Map<String, dynamic>.from(row)).toList();
});

class FacultyLeaveScreen extends ConsumerStatefulWidget { const FacultyLeaveScreen({super.key}); @override ConsumerState<FacultyLeaveScreen> createState() => _FacultyLeaveScreenState(); }
class _FacultyLeaveScreenState extends ConsumerState<FacultyLeaveScreen> {
  DateTime? _from; DateTime? _to; final _reason = TextEditingController(); final _handover = TextEditingController(); bool _saving = false;
  @override void dispose() { _reason.dispose(); _handover.dispose(); super.dispose(); }
  Future<void> _pick(bool start) async { final result = await showDatePicker(context: context, initialDate: start ? (_from ?? DateTime.now()) : (_to ?? _from ?? DateTime.now()), firstDate: DateTime.now().subtract(const Duration(days: 1)), lastDate: DateTime.now().add(const Duration(days: 730))); if (result != null) setState(() { if (start) _from = result; else _to = result; }); }
  String _date(DateTime? value) => value == null ? 'Select date' : '${value.day.toString().padLeft(2, '0')}-${value.month.toString().padLeft(2, '0')}-${value.year}';
  Future<void> _submit() async { if (_from == null || _to == null || _reason.text.trim().isEmpty) return; setState(() => _saving = true); try { await ref.read(dioClientProvider).dio.post('/faculty/me/leave-requests', data: {'start_date': _from!.toIso8601String().substring(0, 10), 'end_date': _to!.toIso8601String().substring(0, 10), 'reason': _reason.text.trim(), 'handover_note': _handover.text.trim()}); _reason.clear(); _handover.clear(); setState(() { _from = null; _to = null; }); ref.invalidate(facultyLeavesProvider); if (mounted) ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Leave request submitted to Management.'))); } catch (error) { if (mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Could not submit request: $error'))); } finally { if (mounted) setState(() => _saving = false); } }
  @override Widget build(BuildContext context) { final state = ref.watch(facultyLeavesProvider); return Scaffold(appBar: AppBar(title: const Text('Faculty leave'), leading: IconButton(onPressed: () => context.go('/faculty'), icon: const Icon(Icons.arrow_back_rounded))), body: ListView(padding: const EdgeInsets.all(16), children: [Container(padding: const EdgeInsets.all(20), decoration: BoxDecoration(borderRadius: BorderRadius.circular(26), gradient: const LinearGradient(colors: [Color(0xFF1C255D), Color(0xFF614FEF)])), child: const Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('TEACHING CONTINUITY', style: TextStyle(color: Color(0xFFBFEFFD), fontWeight: FontWeight.w800)), SizedBox(height: 8), Text('Request leave with a clear handover.', style: TextStyle(color: Colors.white, fontSize: 20, fontWeight: FontWeight.w800))])), const SizedBox(height: 18), Card(child: Padding(padding: const EdgeInsets.all(16), child: Column(children: [Row(children: [Expanded(child: OutlinedButton(onPressed: () => _pick(true), child: Text('From: ${_date(_from)}'))), const SizedBox(width: 10), Expanded(child: OutlinedButton(onPressed: () => _pick(false), child: Text('To: ${_date(_to)}')))]), const SizedBox(height: 12), TextField(controller: _reason, maxLines: 3, decoration: const InputDecoration(labelText: 'Reason')), const SizedBox(height: 12), TextField(controller: _handover, maxLines: 2, decoration: const InputDecoration(labelText: 'Handover note (optional)')), const SizedBox(height: 16), SizedBox(width: double.infinity, child: FilledButton.icon(onPressed: _saving ? null : _submit, icon: _saving ? const SizedBox.square(dimension: 18, child: CircularProgressIndicator(strokeWidth: 2)) : const Icon(Icons.send_rounded), label: const Text('Submit leave request')))]))), const SizedBox(height: 22), Text('My requests', style: Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight: FontWeight.w800)), const SizedBox(height: 8), state.when(loading: () => const Center(child: Padding(padding: EdgeInsets.all(20), child: CircularProgressIndicator())), error: (e, _) => TextButton(onPressed: () => ref.invalidate(facultyLeavesProvider), child: const Text('Retry loading requests')), data: (items) => items.isEmpty ? const Card(child: Padding(padding: EdgeInsets.all(18), child: Text('No leave requests yet.'))) : Column(children: items.map((item) => Card(child: ListTile(leading: const CircleAvatar(child: Icon(Icons.event_note_rounded)), title: Text('${item['start_date']} → ${item['end_date']}'), subtitle: Text(item['reason']?.toString() ?? ''), trailing: Text(item['status']?.toString() ?? 'PENDING', style: const TextStyle(fontWeight: FontWeight.w800)))).toList())))])); }
}
