name: faculty_app
description: EduFlow Faculty App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  go_router: ^13.1.0
  eduflow_core:
    path: ../eduflow_core

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
